Add 's' to the seconds value
Units are required to set the timeout for the helm command.
Helm command --timeout parameter
If there are no units, the following error occurs
Error: invalid argument "1800" for "--timeout" flag: time: missing unit in duration 1800